version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: 
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: |
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/rickybeatus/karsajobs:latest
            echo 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 | docker login ghcr.io -u rickybeatus --password-stdin
            docker push ghcr.io/rickybeatus/karsajobs:latest