version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - name: test-app
        run: go test -v -short --count=1 $(go list ./...)
      - name: build-app-karsajobs
        run: |
          docker build -t karsajobs:latest .
          docker tag karsajobs:latest ghcr.io/rickybeatus/karsajobs:latest
      - name: list-all
        run: ls -a