version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: 
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: build-app-karsajobs
          command: |
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh