version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: 
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image
          command: |
            docker build -t karsajobs .
            docker tag karsajobs ghcr.io/rickybeatus/karsajobs
            echo $DOCKER_PASSWORD | docker login ghcr.io -u rickybeatus --password-stdin
            docker push ghcr.io/rickybeatus/karsajobs

workflows:
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app  
      - build-app-karsajobs
