version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
  test:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build