version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: docker run --rm --interactive hadolint/hadolint < Dockerfile
      - run: go test -v -short --count=1 $(go list ./...)